name: Kernel

on:
  workflow_dispatch: {}
  push:
    branches: ['release-1.4']
    paths:
      - docker-bake.hcl
      - hack/boards/defconfig
      - .github/workflows/kernel.yaml
  schedule:
    - cron: '15 18 * * 2' # 18:15 UTC on Tuesday

jobs:
  kernel:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: none

    outputs:
      digest: ${{ steps.docker.outputs.digest }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: milas
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # we need the local repo contents to get files from `./hack/boards`
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: docker.io/milas/rock5-talos-kernel
          flavor: latest=false
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern=latest
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: docker/bake-action@v2
        with:
          push: true
          pull: true
          targets: kernel
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            *.attest=type=provenance,mode=max
