name: Talos Images

on:
  push:
    branches: [ 'main', 'release-*' ]
    tags:
      - "v*"

env:
  # REGISTRY is used by Talos makefile targets
  REGISTRY: docker.io
  # USERNAME is used by Talos makefile targets
  USERNAME: milas

jobs:
  talos-installer-image:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: none

    strategy:
      matrix:
        board: [rock-5a, rock-5b]

    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # ^^^ populated from mandatory vars for Talos makefile
          # just done to keep in sync, not for flexibility
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # need history for `git describe` to work for Talos `Makefile`
          fetch-depth: 0

      - name: Build and push Talos installer image
        run: make installer
        env:
          PUSH: '1'
          IMAGE_NAME: rock5-talos
          ROCK5_BOARD: ${{ matrix.board }}
          PLATFORM: linux/arm64
          PROGRESS: plain

  # TODO(milas): refactor to split release from eMMC image & use matrix strategy
  talos-emmc-image:
    runs-on: ubuntu-22.04
    needs: talos-installer-image

    if: contains(github.ref, 'refs/tags/')

    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Build Flashable Image for Rock 5B
        run: |
          mkdir -p _out/
          make sbc-rock_5b
        env:
          IMAGE_NAME: rock5-talos
          IMAGE_TAG: ${{ github.ref_name }}-rock-5b
          ROCK5_BOARD: rock-5b

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: _out/metal-rock_5b-arm64.img.xz
          generate_release_notes: true
